### ISSUE TITLE
Unmanaged repos remain after setting purge

### ISSUE THREAD

**Issue by MirthScout** [evenup/evenup-yum#10]
First of all, I'll admit I'm still not a puppet expert so my problem could be user error...

I've installed this module and configured repos via hiera.  The .repo files are created exactly as expected.

I set the purge option to true but I still see .repo files in /etc/yum.repos.d that are not part of my configuration.

My hiera yaml file for this test looks something like this:

classes:
 - yum

yum::gpg_source: 'puppet:///data/yum/gpg'
yum::purge: true
yum::repos:
  'sl6x':
    'descr':    'Scientific Linux 6x - $basearch'
    'baseurl':  'http://my_mirror/SL/6x/$basearch/os/'
    'enabled':  '1'
    'gpgcheck': '1'
    'gpgkey':   'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-sl file:///etc/pki/rpm-gpg/RPM-GPG-KEY-sl6 file:///etc/pki/

This is on a Scientific Linux 6.6 system.

**Comment by jlambert121** [comment]
What version of puppet are you using?

**Comment by jlambert121** [comment]
Would you check version 0.1.1 and see if that takes care of your issue?  I reworked how purges were done.

**Comment by jlambert121** [comment]
I'm closing this as I believe it is fixed in 0.1.1, please let me know if you continue to have issues.
